[default]
now_iso = "@jinja {{this._get_now_iso(this.tz)}}"
start_ts = "@jinja {{this._get_start_ts(this.tz)}}"
tz = "Asia/Kolkata"
logger_name = "the_main_quest"
base_data_path = "@jinja {{this.home_dir}}/Data/THE_MAIN_QUEST"
loki_log_path = "@jinja {{this.base_data_path}}/logs/loki_the_main_quest.log"

[default.todoist_snapshot]
tasks_table = "todoist_tasks"
snapshot_table = "todoist_daily_snapshot"
recurring_tasks_table = "todoist_recurring_tasks"
recurring_log_table = "todoist_recurring_log"
use_test_db = true
